spring:
  application:
    name: eureka-server1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
  #是否注册自身到eureka服务器
    register-with-eureka: true
  #是否从eureka服务器获取注册信息
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/